### ISSUE TITLE
Niektóre komendy - błąd

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#214]
Przy niektórych komendach z /ga, np. /ga nazwa i komendzie /przedluz jest blad.
http://scr.hu/1gy8/pk90h

**Comment by TheMolkaPL** [comment]
Podaj log z konsoli gdy wykonujesz ta komendę.

**Comment by HAMMERxPL** [comment]
[15:24:51] [Server thread/INFO]: x issued server command: /odnow
[15:24:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'odnow' in net.dzikoysk.funnyguilds.command.util.Performer(odnow)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[craftbukkit.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1571]
Caused by: java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.command.ExcValidity.execute(ExcValidity.java:45) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1571]
	... 12 more

**Comment by HAMMERxPL** [comment]
org.bukkit.command.CommandException: Unhandled exception executing 'ga nazwa tag nazwa' in net.dzikoysk.funnyguilds.command.util.Performer(ga)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[craftbukkit.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1571]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161) ~[?:1.7.0_25]
	at java.util.AbstractList$Itr.remove(AbstractList.java:374) ~[?:1.7.0_25]
	at java.util.AbstractCollection.remove(AbstractCollection.java:283) ~[?:1.7.0_25]
	at net.dzikoysk.funnyguilds.command.admin.AxcName.execute(AxcName.java:60) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:80) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
	at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1571]
	... 12 more

**Comment by HAMMERxPL** [comment]
http://przeklej.org/file/AazP8b/error.log

**Comment by Dzikoysk** [comment]
Dobrze ustawiłeś komendy w configu?

**Comment by HAMMERxPL** [comment]
# Nazwy komend
commands:
  guild: 
    name: 'guild'
    aliases: []
  create:
    name: 'zaloz'
    aliases: []
  delete:
    name: 'usun'
    aliases: []
  confirm:
    name: 'potwierdz'
    aliases: []
  invite:
    name: 'zapros'
    aliases: []
  join:
    name: 'dolacz'
    aliases: []
  leave:
    name: 'opusc'
    aliases: []
  kick:
    name: 'wyrzuc'
    aliases: []
  base: 
    name: 'baza'
    aliases:
    - 'dom'
    - 'gdom'
  enlarge: 
    name: 'powieksz'
    aliases: []
  ally: 
    name: 'sojusz'
    aliases: []
  break: 
    name: 'zerwij'
    aliases: []
  info: 
    name: 'info'
    aliases:
    - 'ginfo'
  player: 
    name: 'gracz'
    aliases:
    - 'ranking'
    - 'elo'
    - 'statystyki'
    - 'staty'
    - 'rank'
    - 'punkty'
    - 'pkt'
  top: 
    name: 'top10'
    aliases: []
  validity:
    name: 'odnow'
    aliases: []
  leader:
    name: 'lider'
    aliases: []
  deputy:
    name: 'zastepca'
    aliases: []
  ranking: 
    name: 'topranking'
    aliases: []

  setbase:
    name: 'ustawbaze'
    aliases:
    - 'ustawdom'
    - 'ustawbaza'
  pvp:
    name: 'ff'
    aliases: []

  # Komendy administratora
  admin:
    main: 'ga'
    add: 'ga dodaj'
    delete: 'ga usun'
    kick: 'ga wyrzuc'
    teleport: 'ga tp'
    points: 'ga points'
    kills: 'ga kills'
    deaths: 'ga deaths'
    ban: 'ga ban'
    lives: 'ga zycia'
    move: 'ga przenies'
    unban: 'ga unban'
    validity: 'ga przedluz'
    name: 'ga nazwa'

**Comment by Dzikoysk** [comment]
No oki, na pierwszy rzut oka wygląda dobrze. Czyli trzeba zaliczyć do bugów :C
