### ISSUE TITLE
błąd w konsoli

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#215]
Jak jakiś gracz kogoś zabije to pojawia się błąd w konsoli:
[19:38:43] [IndependentThread/WARN]: java.lang.ClassCastException: net.dzikoysk.funnyguilds.basic.User cannot be cast to net.dzikoysk.funnyguilds.basic.Guild
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:54)
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)
[19:38:43] [IndependentThread/WARN]: java.lang.ClassCastException: net.dzikoysk.funnyguilds.basic.User cannot be cast to net.dzikoysk.funnyguilds.basic.Guild
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:54)
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[19:38:43] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)

(Wersja 3.5.1 NewYear)

**Comment by Dzikoysk** [comment]
#213
