### ISSUE TITLE
Błąd przy założeniu gildii

### ISSUE THREAD

**Issue by Esa123** [Dzikoysk/FunnyGuilds#230]
[16:04:21 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R1.entity.CraftPlayer cannot be cast to net.dzikoysk.funnyguilds.basic.OfflineUser
[16:04:21 WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:74)
[16:04:21 WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[16:04:21 WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)

**Comment by TheMolkaPL** [comment]
Błąd już znany z #213
