### ISSUE TITLE
LOGI Z CONSOLI!

### ISSUE THREAD

**Issue by Szeder32** [Dzikoysk/FunnyGuilds#234]
Błąd przy tworzeniu gildii:

[16:26:50 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R1.entity.CraftPlayer cannot be cast to net.dzikoysk.funnyguilds.basic.OfflineUser
[16:26:50 WARN]:at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:74)
[16:26:50 WARN]:at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[16:26:50 WARN]:at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)

**Comment by TheMolkaPL** [comment]
Błąd już znany z #213
