### ISSUE TITLE
Bład

### ISSUE THREAD

**Issue by TuKaN1337** [Dzikoysk/FunnyGuilds#236]
[FunnyGuilds] Task #1952 for FunnyGuilds v3.9.1 Cleaned generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:492) ~[spigot.jar:git-Spigot-1604]
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:200) ~[spigot.jar:git-Spigot-1604]
        at net.dzikoysk.funnyguilds.command.ExcBase$1.run(ExcBase.java:97) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1604]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1604]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1604]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1604]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1604]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1604]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1604]
>

**Comment by TheMolkaPL** [comment]
Ustawiłeś home gildii?
