### ISSUE TITLE
Problem z 1.8 (logowanie?)

### ISSUE THREAD

**Issue by czatjaw** [Dzikoysk/FunnyGuilds#252]
**Wchodze na serwer i wyskakuje mi bład**
**SILNIK: This server is running CraftBukkit version git-Spigot-e497721-96d09e3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)**

_[07:36:18] [User Authenticator #1/INFO]: UUID of player nickis 5atecrd8-cb94-4e94-9dc0-effd7f4c592d
[07:36:18] [IndependentThread/WARN]: Exception in thread "IndependentThread" 
[07:36:18] [IndependentThread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/util/com/mojang/authlib/GameProfile
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.OfflineUser.init(OfflineUser.java:156)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.basic.OfflineUser.<init>(OfflineUser.java:33)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.PlayerListManager.send(PlayerListManager.java:45)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.PlayerList.send(PlayerList.java:96)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.element.PlayerListManager.updatePlayers(PlayerListManager.java:24)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:46)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[07:36:18] [IndependentThread/WARN]: 	at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)
[07:36:18] [IndependentThread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.com.mojang.authlib.GameProfile
[07:36:18] [IndependentThread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[07:36:18] [IndependentThread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[07:36:18] [IndependentThread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[07:36:18] [IndependentThread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[07:36:18] [IndependentThread/WARN]: 	... 8 more
[07:36:18] [Server thread/INFO]: nick[/0.0.0.0:00000] logged in with entity id 0 at ([spawn] -34.415813958617974, 48.0, 28.619318605729028)
[07:36:20] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[07:36:20] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 21
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
	at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more_

**Comment by Dzikoysk** [comment]
1.8 nie jest wspierane. Jedynie serwer 1.7.x - 1.8 (pozwalający jedynie dołączyć do gry z 1.8) będzie działał

**Comment by TheMolkaPL** [comment]
Może wprowadź support dla Spigota 1.8?

**Comment by czatjaw** [comment]
Powoli przestawiają się pod 1.8 może i czas na Gildie ;) ?

**Comment by Dzikoysk** [comment]
Na razie wprowadzam jedynie poprawki, bo i czasu na gildie mam mało
