### ISSUE TITLE
Błędy  [3.9.3]

### ISSUE THREAD

**Issue by sokrates1231** [Dzikoysk/FunnyGuilds#254]
[18:52:32] [Craft Scheduler Thread - 1917/WARN]: Exception in thread "Craft Scheduler Thread - 1917" 
[18:52:32] [Craft Scheduler Thread - 1917/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 18714856
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: packet_handler
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153)
	at net.dzikoysk.funnyguilds.util.reflect.PacketExtension.registerPlayer(PacketExtension.java:67)
	at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[18:51:53] [Craft Scheduler Thread - 1909/WARN]: Exception in thread "Craft Scheduler Thread - 1909" 
[18:51:53] [Craft Scheduler Thread - 1909/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 18681074
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: packet_handler
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153)
	at net.dzikoysk.funnyguilds.util.reflect.PacketExtension.registerPlayer(PacketExtension.java:67)
	at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[00:22:01] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[00:22:01] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 3002
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: packet_handler
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160)
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153)
	at net.dzikoysk.funnyguilds.util.reflect.PacketExtension.registerPlayer(PacketExtension.java:67)
	at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Dzikoysk** [comment]
Podaj pluginy

**Comment by sokrates1231** [comment]
Proszę: http://iv.pl/images/81499337906638612713.jpg

**Comment by Dzikoysk** [comment]
Hmmmm... no ok. Dziwne, że gracz nie ma tego kanału od packetów :O Coś się jutro pomyśli

**Comment by x0dus** [comment]
u mnie tak wywala 

[07:42:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 9974
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: packet_handler
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905)
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160)
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153)
        at net.dzikoysk.funnyguilds.util.reflect.PacketExtension.registerPlayer(PacketExtension.java:67)
        at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

i crashuje klienta mc

---- Minecraft Crash Report ----
// I'm sorry, Dave.
 
 
 
 
Time: 18.01.15 08:12
Description: Unexpected error
 
 
 
 
java.lang.NullPointerException: Unexpected error
at ayr.d(SourceFile:169)
at biv.a(SourceFile:1134)
at hr.a(SourceFile:99)
at hr.a(SourceFile:13)
at ef.a(SourceFile:164)
at biy.e(SourceFile:212)
at azd.o(SourceFile:1281)
at azd.ad(SourceFile:753)
at azd.e(SourceFile:704)
at net.minecraft.client.main.Main.main(SourceFile:103)
 
 
 
 
 
 
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
 
 
 
-- Head --
Stacktrace:
at ayr.d(SourceFile:169)
at biv.a(SourceFile:1134)
at hr.a(SourceFile:99)
at hr.a(SourceFile:13)
at ef.a(SourceFile:164)
at biy.e(SourceFile:212)
 
 
 
 
-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [bje['Jpump'/201, l='MpServer', x=8,50, y=66,62, z=8,50]]
Chunk stats: MultiplayerChunkCache: 0, 0
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (-18,69,-18), Chunk: (at 14,4,14 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 1 total; [bje['Jpump'/201, l='MpServer', x=8,50, y=66,62, z=8,50]]
Retry entities: 0 total; []
Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"972b4c1":1025) <- Spigot
Server type: Non-integrated multiplayer server
Stacktrace:
at biz.a(SourceFile:284)
at azd.b(SourceFile:1951)
at azd.e(SourceFile:718)
at net.minecraft.client.main.Main.main(SourceFile:103)
 
 
 
 
-- System Details --
Details:
Minecraft Version: 1.7.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_55, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 366954824 bytes (349 MB) / 427294720 bytes (407 MB) up to 954728448 bytes (910 MB)
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
AABB Pool Size: 52281 (2927736 bytes; 2 MB) allocated, 52281 (2927736 bytes; 2 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: 1.7.2
LWJGL: 2.9.0
OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.09, NVIDIA Corporation
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by sokrates1231** [comment]
Na pewno każdemu te błędy wywala.

**Comment by TheMolkaPL** [comment]
#254

**Comment by x0dus** [comment]
Naprawicie ten blad ? bo widze ze blad zgloszony zostal 6 dni temu

**Comment by Dzikoysk** [comment]
Na razie nie mam czasu, zobaczy się w tygodniu
