### ISSUE TITLE
Bledy w konsolce najnowsza wersja gildii

### ISSUE THREAD

**Issue by xW0LFx** [Dzikoysk/FunnyGuilds#257]
[17:07:05 WARN]: Exception in thread "Craft Scheduler Thread - 16"
[17:07:05 WARN]: org.apache.commons.lang.UnhandledException: Plugin FunnyGuilds v3.9.3 Cleaned generated an exception while executing task 5439
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.util.NoSuchElementException: packet_handler
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905)
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160)
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153)
        at net.dzikoysk.funnyguilds.util.reflect.PacketExtension.registerPlayer(PacketExtension.java:67)
        at net.dzikoysk.funnyguilds.listener.PlayerJoin$1.run(PlayerJoin.java:33)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by TheMolkaPL** [comment]
Już masz #254 - jak robisz nowy issue to sprawdź czy już takowy istnieje, bo się robi po woli z tego mpcforum :baby:
