### ISSUE TITLE
Błąd - Komenda /przedluz

### ISSUE THREAD

**Issue by Kenix97** [Dzikoysk/FunnyGuilds#258]
Kiedy gracze mają gildię i chcą ją przedłużyć to wyskakuje "An internal error bla bla wiesz co dalej"..
I mały spam na konsoli podczas napisania tego jest.
Wersja: Testowałem na 3.5.1 NewYear i Cleaned 3.9.3

**Comment by Kenix97** [comment]
[14:42:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'przedluz' in net.dzikoysk.funnyguilds.command.util.Performer(przedluz)
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:99) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:706) ~[craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:984) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:829) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
Caused by: java.lang.NullPointerException
        at net.dzikoysk.funnyguilds.command.ExcValidity.execute(ExcValidity.java:46) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
        ... 12 more

**Comment by Dzikoysk** [comment]
Error jest z wersji 3.9.3? I czy masz "validityWhen" w messages.yml

**Comment by Kenix97** [comment]
A dzięki! XD I jeszcze taki mały problemik.. Otóż (gdy był jeszcze ten błąd) to gdy aktualizowałem plugin z wersji 3.5.1 na 3.9.3 to były Ender Crystale i nie mogłem ich wgl usunąć.. Gdy wyłączyłem plugin (komenda od innego pluginu) to one znikneły. W config.yml mam ustawione, że bedrock po założeniu gildii ma być.. A jest i to i to. Co robić?

**Comment by Dzikoysk** [comment]
To jest akurat bug :P Nie martw się, to są sztuczne crystale. Jak poprawię, to bez problemu wszystkie znikną :)

**Comment by Kenix97** [comment]
Spoczko :D

**Comment by Kenix97** [comment]
A i żeby nie robić kolejnego tematu bo to jest związane z tym:
Jak zaktualizuję do wersji 1.9.4 to usuną się wszystkie ender crystale? A i czy nie będzie jakichś tam błędów na silniku Spigot 1.7.2? Bo sam nw czy aktualizować do nowszej, a mnie to wkurza gdy mnie aktualizacja męczy przy dołączaniu xD
