### ISSUE TITLE
crash mc przy wchodzeniu na serwa

### ISSUE THREAD

**Issue by x0dus** [Dzikoysk/FunnyGuilds#263]
16:07:37 [SEVERE] [Lara1325] <-> DownstreamBridge <-> [glowny] - encountered exception
java.lang.IllegalArgumentException: Team fly already exists in this scoreboard
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:182)
at net.md_5.bungee.protocol.packet.Team.handle(Team.java:106)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Thread.java:745)

**Comment by zorro8003PL** [comment]
To chyba nie jest z FunnyGuilds

**Comment by x0dus** [comment]
uwierz mi ze jest

**Comment by x0dus** [comment]
i tak przy okazji gadalem z jednych developerow spigota niestety nie pomogl a o to rozmowa
http://screenshooter.net/2266451/tfpkffl

**Comment by Dzikoysk** [comment]
Nie mam pojęcia na jakiej zasadzie działają scoreboardy w bungeecord. Wiem natomiast, że na pewno funnyguilds za każdym razem przed tworzeniem teamu sprawdza, czy takowy czasem już nie istnieje. Jaka wersja serwera?

**Comment by x0dus** [comment]
[22:12:24 INFO]: This server is running CraftBukkit version git-Spigot-1543 (MC: 1.7.9) (Implementing API version 1.7.9-R0.3-SNAPSHOT)

i

http://ci.md-5.net/job/BungeeCord/1037/

**Comment by x0dus** [comment]
dobra wiem w czym problem lezy Dzikoysk jesli znasz dzialanie bungecord to wiesz ze laczysz sie na proxy wysyla cie na serwer lobby z lobby idziesz drugi serwer na ktorym sa twoje gildie i wiec tak bungeecord wysyla chyba informacje z scoreboard z lobby na ten drugi serwer i dlatego craszuje niewiem czy znajdziesz rozwiazanie jak to obejsc moze jakis osobny plugin na lobby ktory bo wyjsciu z lobby by resetowal scoreboard i wpuszczal na swiezo na drugi serwer ... niemam pojecia

**Comment by x0dus** [comment]
Dzikoysk pisalem o bugu na bungee cord twierdza ze to bug z twojego pluginu moze bys sie zajol bugiem tym bo ludzie ktorzy maja bugneecord a sa to wieksze serwery napewno nie skorzystaja z twojego pluginu
http://screenshooter.net/2266451/ewpnvox

prosze cie o naprawe tego :(

**Comment by Dzikoysk** [comment]
Nie wiem co robi bungeecord, ale widocznie nie jestem w stanie sprawdzić, czy team istnieje lub też nie:
<pre>Team team = scoreboard.getTeam(to.getTag());
if(team == null) team = scoreboard.registerNewTeam(to.getTag());
</pre>

**Comment by x0dus** [comment]
a moze bys napisal jakis dodatek do plugina oddzielny ktory wgrywasz na lobby i by on powodowal ze wychodzac/przechodzac z lobby na drugi serwer poprostu wpuszcza gracza z pustym scoreboard bo widzisz co sie dzieje crashuje gracza przez blad scoreborad ze taki team istnieje

**Comment by Dzikoysk** [comment]
Na razie nie mam czasu na fg, przygotowuję się do wyjazdu na tydzień. Możesz spróbować z https://github.com/EastWestFM/RevoGuild, on używa do tego wszystkiego zupełnie innego systemu, być może na bungee załapie

**Comment by x0dus** [comment]
Revo juz bralem pelno bugow kicki z serwera przy 50 online i jak zrobisz reloga to ci znikaja itemy ktore trzymales w reku i autor stracil zainteresowanie plugsem poczekam az ty cos wykombinujesz
