### ISSUE TITLE
nie mozna usunac gildi

### ISSUE THREAD

**Issue by x0dus** [Dzikoysk/FunnyGuilds#265]
[18:56:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ga usun ZUO' in net.dzikoysk.funnyguilds.command.util.Performer(ga)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:1015) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:845) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot1543.jar:git-Spigot-1543]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:393) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:120) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:104) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:88) ~[spigot1543.jar:git-Spigot-1543]
        at net.dzikoysk.funnyguilds.basic.util.GuildUtils.deleteGuild(GuildUtils.java:28) ~[?:?]
        at net.dzikoysk.funnyguilds.command.admin.AxcDelete.execute(AxcDelete.java:45) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:80) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
        at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot1543.jar:git-Spigot-1543]
        ... 12 more

**Comment by zorro8003PL** [comment]
Bo Ty chyba wpisywałeś tą komende przez konsole, a ta komenda nie działa z poziomu konsoli.

**Comment by x0dus** [comment]
nie dzialalo bo /plugman reload funnyguilds i wtedy plugin swiruje trzeba zrobic res serwera
