### ISSUE TITLE
Błąd w FG v3.9.6.4

### ISSUE THREAD

**Issue by Kenix97** [Dzikoysk/FunnyGuilds#298]
Witam. Otóż jak chciałem wgrać FunnyGuilds na moim testowym serwerze, wyskoczyły błędy:

[10:05:56] [Server thread/INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.6.4 Cleaned
[10:05:56] [Server thread/WARN]: java.io.FileNotFoundException: plugins\FunnyGuilds\data\funnyguilds.dat (System nie może odnaleźć określonej ścieżki)
[10:05:56] [Server thread/WARN]: 	at java.io.FileInputStream.open(Native Method)
[10:05:56] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.Files$FileByteSource.openStream(Files.java:127)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.Files$FileByteSource.openStream(Files.java:117)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:404)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.CharSource.getInput(CharSource.java:87)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.CharSource.getInput(CharSource.java:63)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.CharStreams.readLines(CharStreams.java:325)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.Files.readLines(Files.java:747)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.util.com.google.common.io.Files.readLines(Files.java:718)
[10:05:56] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.util.configuration.util.ConfigurationUtils.getLines(ConfigurationUtils.java:37)
[10:05:56] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:25)
[10:05:56] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.util.Reloader.init(Reloader.java:19)
[10:05:56] [Server thread/WARN]: 	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:59)
[10:05:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugins(CraftServer.java:355)
[10:05:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.<init>(CraftServer.java:312)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PlayerList.<init>(PlayerList.java:63)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.DedicatedPlayerList.<init>(SourceFile:14)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:126)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:426)
[10:05:56] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[10:05:56] [Server thread/ERROR]: null initializing FunnyGuilds v3.9.6.4 Cleaned (Is it up to date?)
java.lang.NullPointerException
	at net.dzikoysk.funnyguilds.util.configuration.ConfigurationParser.run(ConfigurationParser.java:33) ~[?:?]
	at net.dzikoysk.funnyguilds.util.configuration.ConfigurationParser.<init>(ConfigurationParser.java:21) ~[?:?]
	at net.dzikoysk.funnyguilds.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:26) ~[?:?]
	at net.dzikoysk.funnyguilds.util.Reloader.init(Reloader.java:19) ~[?:?]
	at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugins(CraftServer.java:355) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.<init>(CraftServer.java:312) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.PlayerList.<init>(PlayerList.java:63) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:426) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]

I się zdziwiłem, ponieważ skoro system nie może odnaleźć ścieżki to plugin powinien sam zrobić ten nowy folder z funnyguilds.dat lecz tego nie zrobił.. Mam silnik MC CraftBukkit 1.7.2.

**Comment by TheMolkaPL** [comment]
Musisz stworzyć plik `funnyguilds.dat` w folderze `plugins\FunnyGuilds\data`.
