### ISSUE TITLE
Kolejny błąd w FG 3.6.9.3!

### ISSUE THREAD

**Issue by Kenix97** [Dzikoysk/FunnyGuilds#301]
Otóż mam problem.. Po założeniu gildii kickneło mnie z serwera (tylko) i jak chcę dołączyć pisze: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: The received string length is longer than maximum allowed (19 > 16). Co robić!?

**Comment by Kenix97** [comment]
Dodam jeszcze, że jak wpisuje (po tym błędzie) komende /ga to wyskakują mi błędy:

[14:25:55 WARN]: Unexpected exception while parsing console command "ga"
org.bukkit.command.CommandException: Unhandled exception executing 'ga' in net.dzikoysk.funnyguilds.command.util.Performer(ga)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:179) ~[mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:706) ~[mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchServerCommand(CraftServer.java:693) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.DedicatedServer.aw(DedicatedServer.java:309) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:274) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
at net.dzikoysk.funnyguilds.command.admin.AxcMain.execute(AxcMain.java:17) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
... 7 more

**Comment by Kenix97** [comment]
Był błąd z tablistą tylko. DO ZAMKNIĘCIA! A i jak coś to są błędy gdy się napisze komendę /ga na konsoli lub kiedy bd miało się gildię i wpisze się /powieksz a opcja bd wyłączona.
