### ISSUE TITLE
Błąd podczas usuwania gildii.

### ISSUE THREAD

**Issue by Kenix97** [Dzikoysk/FunnyGuilds#307]
Witam. Mam problem, otóż gdy usuwam gildię wyskakują mi błędy:

[17:42:00 WARN]: [FunnyGuilds] Task #2239344 for FunnyGuilds v3.9.6.3 Cleaned generated an exception
java.lang.NullPointerException
at net.dzikoysk.funnyguilds.basic.util.GuildUtils$1.run(GuildUtils.java:38) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:614) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [mc.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]

..i gildia zostaje usunięta. Dodam, że bedrock (ustawiony w config.yml) nadal jest na swoim miejscu.
Pomoże mi ktoś to naprawić? :/

**Comment by TheMolkaPL** [comment]
https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/basic/util/GuildUtils.java#L38

`getCenter()` lub `getBlock()` może być nullem.

**Comment by Dzikoysk** [comment]
#3.9.6.3, także nawet nie patrzę. Zobaczę #3.9.9, to zerkne :)

**Comment by Kenix97** [comment]
Ja nie chcę wgrywać 3.9.9 bo jest ten system skryptów i więcej tego wszystkiego nawalone.. Ja szukam ciągle wersji takiej co było by to co mi jest potrzebne bez jakichś dodanych rzeczy :/

**Comment by Dzikoysk** [comment]
A co zmienia to, że dodane zostały skrypty?

**Comment by Kenix97** [comment]
Nie wiem.. A będą one do czegoś przydatne? ;d
