### ISSUE TITLE
Usuwanie gildii 

### ISSUE THREAD

**Issue by ghost** [dzikoysk/FunnyGuilds#318]
Błąd przy usuwaniu gildii.

[x] [Server thread/INFO]: x issued server command: /usun
[x] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'usun' in net.dzikoysk.funnyguilds.command.util.Performer(usun)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[craftbukkit.jar:git-Spigot-1571]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1571]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1571]
Caused by: java.lang.NoClassDefFoundError: net/dzikoysk/funnyguilds/data/util/ConfirmationList
    at net.dzikoysk.funnyguilds.command.ExcDelete.execute(ExcDelete.java:30) ~[?:?]
    at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
    at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
    at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1571]
    ... 12 more

**Comment by Dzikoysk** [comment]
Reloadowałeś serwer czy cuś, bo masz dziurę w ClassLoaderze

**Comment by zorro8003PL** [comment]
Ja też mam taki błąd w konsoli przy usuwaniu gildii :o:

**Comment by CzlowiekKuktas** [comment]
Nic nie przeładowywałem.

**Comment by Dzikoysk** [comment]
To nie jest wina fg, tylko classloadera z bukkita niestety
