### ISSUE TITLE
Błąd przy uruchomieniu pluginu

### ISSUE THREAD

**Issue by HerQles** [dzikoysk/FunnyGuilds#339]
Witam
Pilnie potrzebowałem fajnego pluginu po polsku na gildie znalazłem ten ale mam ktopot gdyż plugin nie działa. Oto log z konsoli
[19:42:53] [Server thread/INFO]: [FunnyGuilds] Enabling FunnyGuilds v3.9.9.1 Cleaned
[19:42:53] [Server thread/INFO]: [FunnyGuilds] Available Processors: 24
[19:42:53] [Server thread/INFO]: [FunnyGuilds] Active Threads: 13
[19:42:53] [Server thread/ERROR]: Error occurred while enabling FunnyGuilds v3.9.9.1 Cleaned (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/util/com/google/common/base/Charsets
    at net.dzikoysk.panda.util.configuration.util.ConfigurationUtils.getLines(ConfigurationUtils.java:38) ~[?:?]
    at net.dzikoysk.panda.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:25) ~[?:?]
    at net.dzikoysk.funnyguilds.data.Settings.update(Settings.java:183) ~[?:?]
    at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:178) ~[?:?]
    at net.dzikoysk.funnyguilds.data.Settings.getInstance(Settings.java:438) ~[?:?]
    at net.dzikoysk.funnyguilds.data.Manager.<init>(Manager.java:22) ~[?:?]
    at net.dzikoysk.funnyguilds.FunnyGuilds.onEnable(FunnyGuilds.java:72) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~inecraft_server.jar:git-Spigot-13716d9-0899683]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) inecraft_server.jar:git-Spigot-13716d9-0899683]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

Proszę o pomoc albo namiary na jakiś inny plugin na gildie, klany, frakcje po polsku
Pozdrawiam

**Comment by xVacuum** [comment]
FunnyGuilds nie jest, i prawdopodobnie nie będzie na wersję 1.8

**Comment by HerQles** [comment]
Dzięki za pomoc.
Niestety ja nie jestem w stanie tego pozmieniać gdyż się nie znam na tym. Po za tym chyba zrobię własną gildię jako skrypt. Będzie łatwiej.
Pozdrawiam.
