### ISSUE TITLE
Błąd wykonywanie komendy z konsoli

### ISSUE THREAD

**Issue by TheU5erPL** [dzikoysk/FunnyGuilds#348]
Po wpisaniu komendy /ga w konsoli wywala błędy:

Unexpected exception while parsing console command "ga"
org.bukkit.command.CommandException: Unhandled exception executing 'ga' in net.dzikoysk.funnyguilds.command.util.Performer(ga)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R4.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
at net.dzikoysk.funnyguilds.command.admin.AxcMain.execute(AxcMain.java:17) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
... 7 more

Głównie zależałoby mi na możliwości użycia /ga unban z konsoli.

**Comment by TheMolkaPL** [comment]
Zbędny cast do `Player` w https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/command/admin/AxcMain.java
