### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by filipqw** [Dzikoysk/FunnyGuilds#349]
witam mam problem mam mc 1.7.4 i wgrywam funnyguild i nie dziala wogole nie robi folderu i server go nie czyta

**Comment by TheMolkaPL** [comment]
Podaj swoje logi z konsoli z włączania serwera. Uruchamiaj na minimum 1.7.5 ze względu na wprowadzone w serwer UUID.

**Comment by filipqw** [comment]
[16:31:36] [Server thread/INFO]: Starting minecraft server version 1.7.9
[16:31:36] [Server thread/INFO]: Loading properties
[16:31:36] [Server thread/INFO]: Default game type: SURVIVAL
[16:31:36] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1450 (MC: 1.7.9) (Implementing API version 1.7.9-R0.1-SNAPSHOT)
[16:31:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:31:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:31:36] [Server thread/INFO]: Generating keypair
[16:31:36] [Server thread/INFO]: Starting Minecraft server on 185.5.99.128:20401
[16:31:37] [Server thread/ERROR]: Could not load 'plugins/FunnyGuilds.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 51.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-1450]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-1450]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-1450]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugins(CraftServer.java:360) [craftbukkit.jar:git-Spigot-1450]
	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:135) [craftbukkit.jar:git-Spigot-1450]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:450) [craftbukkit.jar:git-Spigot-1450]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1450]
Caused by: java.lang.UnsupportedClassVersionError: net/dzikoysk/funnyguilds/FunnyGuilds : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_31]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643) ~[?:1.6.0_31]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.6.0_31]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277) ~[?:1.6.0_31]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73) ~[?:1.6.0_31]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212) ~[?:1.6.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_31]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205) ~[?:1.6.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Spigot-1450]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Spigot-1450]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323) ~[?:1.6.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268) ~[?:1.6.0_31]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_31]
	at java.lang.Class.forName(Class.java:270) ~[?:1.6.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit.jar:git-Spigot-1450]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[craftbukkit.jar:git-Spigot-1450]
	... 6 more


logi i juz jest zainstalowy spigot

**Comment by TheMolkaPL** [comment]
Zaktualizuj Javę do najlepiej starszej wersji.

**Comment by filipqw** [comment]
Teraz dziala tylko teraz mam inny problem dodaje mi znaki zapytania pod tab

**Comment by Dzikoysk** [comment]
https://github.com/Dzikoysk/FunnyGuilds/issues/203
