### ISSUE TITLE
Crashe clienta przez fg.

### ISSUE THREAD

**Issue by MetaX96** [Dzikoysk/FunnyGuilds#353]
Na moim serwerze crashowało clienta osobom wchodzącym na serwer.  Już za pierwszą próbą zdarzał się crash,a jeśli udało się wejść to za drugim prawie zawsze crash. Po usunięciu pluginu FunnyGuilds problem zniknął jak ręką odjął. Proszę o pomoc w rozwiazaniu problemu z owym pluginem.

log z clienta:

```
[Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking screen
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1615) ~[azd.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:917) ~[azd.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835) [azd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:103) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.scoreboard.Scoreboard.func_96511_d(SourceFile:169) ~[ayr.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1562) ~[biv.class:?]
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:99) ~[hr.class:?]
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:13) ~[hr.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197) ~[ef.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:76) ~[bbe.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1601) ~[azd.class:?]
	... 9 more
```

Crash report:
http://wklej.org/id/1780446/

**Comment by TheMolkaPL** [comment]
Spróbuj przywrócić tablistę do domyślnego wyglądu.

**Comment by MetaX96** [comment]
Na domyślnych ustawieniach pluginu, po usunięciu folderu, wszedłem na serwer za 7 razem. Tablista jest domyślna oczywiście, co jest oczywiste.

**Comment by TheMolkaPL** [comment]
Czy można poprosić o informację o wersji serwera oraz klienta?

**Comment by MetaX96** [comment]
Wersja serwera Spigot 1.7.5-R0.1 #1387 a klienta 1.7.2, ale crashe występują na wszystkich wersjach 1.7.x. Zauważyłem też, że po zmianie wersji java z 7 na 8, częstotliwość crashy zmalała.

**Comment by MetaX96** [comment]
Problemem był prawdopodobnie konflikt z pluginem HealthBar. Dzięki za pomoc. 
Zamykam.
