### ISSUE TITLE
Blad 1.8 z dzialaniem

### ISSUE THREAD

**Issue by Lasot** [Dzikoysk/FunnyGuilds#357]
Po wlaczeniu serwera z pluginem konsola zostaje za spamowana a plugin nie dziala. Pomocy. ponzej kod bledu z konsoli;

[FunnyGuilds] Disabling FunnyGuilds v3.9.9 Cleaned
[01:43:00 ERROR]: Error occurred while disabling FunnyGuilds v3.9.9 Cleaned (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
        at net.dzikoysk.funnyguilds.FunnyGuilds.onDisable(FunnyGuilds.java:113) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[Craftbukkit.jar:git-Bukkit-1092acb]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:351) [Craftbukkit.jar:git-Bukkit-1092acb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [Craftbukkit.jar:git-Bukkit-1092acb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:416) [Craftbukkit.jar:git-Bukkit-1092acb]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:328) [Craftbukkit.jar:git-Bukkit-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:422) [Craftbukkit.jar:git-Bukkit-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Craftbukkit.jar:git-Bukkit-1092acb]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[Craftbukkit.jar:git-Bukkit-1092acb]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[Craftbukkit.jar:git-Bukkit-1092acb]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        ... 9 more

**Comment by TheMolkaPL** [comment]
FunnyGuilds nie wspiera Minecraft 1.8.
Możesz spojrzeć na [moją aktualizację](https://github.com/TheMolkaPL/FunnyGuilds), jednak nie posiada ona tablisty.
