### ISSUE TITLE
Błędy, przez co nie działa plugin

### ISSUE THREAD

**Issue by Cysiek78** [dzikoysk/FunnyGuilds#363]
Mam nie długo otwarcie serwera i postanowiłem sprawdzić czy wszystko działa. Wpisałem /g i nic 

```
05:40:46 WARN]: java.lang.NullPointerException
[05:40:46 WARN]: at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[05:40:46 WARN]:    at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)
```

O co może chodzić? proszę o szybką odp.

**Comment by TheMolkaPL** [comment]
Prawdopodobnie błąd połączenia z bazą danych.
