### ISSUE TITLE
Problem z zapisem gildii i protocolem lib

### ISSUE THREAD

**Issue by Murzyneczka** [dzikoysk/FunnyGuilds#364]
A więc tak w konfigu mam ustawione aby co minutę zapisywało dane na flat, jednak nie zapisują się przez co gildie znikają. W logach wyskakuje mi takie coś

```
[14:57:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'g itemy' in net.dzikoysk.funnyguilds.command.util.Performer(g)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:184) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:701) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:956) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
Caused by: java.lang.NullPointerException
    at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.call(ExecutorCaller.java:83) ~[?:?]
    at net.dzikoysk.funnyguilds.command.util.ExecutorCaller.onCommand(ExecutorCaller.java:104) ~[?:?]
    at net.dzikoysk.funnyguilds.command.util.Performer.execute(Performer.java:23) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    ... 12 more
```

Nie wiem o co chodzi z tym.
Drugim problemem jest Protocol LIB który jest wymagany do zamaskowania liczby graczy. Gdy go wgrywam tablista zmienia się na zwyczajną minecraftową, a tutaj jest log

```
[14:53:54] [Server thread/ERROR]: Could not load 'plugins/FakePlayers.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugins(CraftServer.java:355) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.reload(CraftServer.java:797) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.Bukkit.reload(Bukkit.java:288) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:701) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:956) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-9-gaceeb44-b3091jnks]
```

**Comment by TheMolkaPL** [comment]
1. Jest to bug. Brakuje sprawdzania czy zmienna `main` nie jest nullem. https://github.com/dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/command/util/ExecutorCaller.java#L83

2. Problem leży po stronie pluginu `FakePlayers`.

**Comment by Murzyneczka** [comment]
A jest jakieś rozwiązanie na te zapisywanie?

**Comment by TheMolkaPL** [comment]
Zapisujesz w MySQL czy pliku?

**Comment by Murzyneczka** [comment]
W pliku
